name: Generate Profile Assets

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      # Generate Snake SVG
      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?color_snake=#00F2FE&color_dots=#0d1117,#161b22,#003865,#0066b2,#00f2fe

      # Generate Streak Stats SVG
      - name: Generate Streak Stats SVG
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          user: ${{ github.repository_owner }}
          theme: dark
          background: 0d1117
          ring: 00f2fe
          fire: 00f2fe
          currStreakNum: ffffff
          currStreakLabel: c9d1d9
          sideNums: ffffff
          sideLabels: c9d1d9
          dates: c9d1d9
          hide_border: true
          output_path: dist/streak-stats.svg

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
